import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "First Next Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>this is header</h1>
        <div className="flex justify-around">
          <div>
            <h1>side menu</h1>
          </div>
          <div>{children}</div>
        </div>
        <h1>this is footer</h1>
      </body>
    </html>
  );
}
