"use client";
import CustomNavbar from "./components/CustomNavbar";
import "./globals.css";
import { Inter } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";
import Footer from "./components/Footer";
import { ToastContainer } from "react-toastify";
import UserProvider from "@/context/userProvider";
import store from "./redux/store/store";
import { Provider } from "react-redux";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Work Manager Project",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <UserProvider>
            <ToastContainer />
            <CustomNavbar />

            <div className="mt-2">{children}</div>

            <Footer />
          </UserProvider>
        </Provider>
      </body>
    </html>
  );
}
